домашка по тестам version1.2
StasPoltavets/stasnialvPoltavets pull request #12
Opened 2023-01-04 15:48 UTC by StasPoltavets

домашка 18, три таски

2023-01-04 19:57 UTC, Protesiani requested changes

2023-01-04 19:57 UTC, Protesiani commented on src/test/java/SelectorTest/CheckBoxTest.java
> +        }
"потім вибрати обидва" - потрібно зробити

2023-01-04 19:57 UTC, Protesiani commented on src/test/java/SelectorTest/CheckBoxTest.java
> +                System.out.println("Selected Checkbox");
в принципі ок, але як зрозуміти про який чекбокс йде мова?

2023-01-04 19:57 UTC, Protesiani commented on src/test/java/SelectorTest/LoginTest.java
> +        driver.findElement(By.id("password")).sendKeys("0000");
тут навмисно неправильні логін пароль?

2023-01-04 19:57 UTC, Protesiani commented on src/test/java/SelectorTest/LoginTest.java
> +        Assert.assertEquals(driver.findElement(By.cssSelector(".flash.success")).getText(), "You logged into a secure area\n" + "×");
якщо буде некоректний логін замість коректного, то тест впаде на driver.findElement, а не на Assert.assertEquals. А як зробити щоб падав саме на Assert'і?

2023-01-05 09:04 UTC, StasPoltavets commented on src/test/java/SelectorTest/LoginTest.java
> +        driver.findElement(By.id("password")).sendKeys("0000");
так

2023-01-06 17:09 UTC, Protesiani approved these changes

2023-01-08 13:23 UTC, merged